# Generated by Django 6.0.5 on 2026-05-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubdivisionAlertImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField(unique=True)),
                ('image', models.ImageField(upload_to='alert_images/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('day_number',),
            },
        ),
    ]
