# Generated by Django 6.0.5 on 2026-05-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertsapp', '0002_subdivisionalertimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictAlertImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=100)),
                ('day_number', models.IntegerField()),
                ('image', models.ImageField(upload_to='district_alert_images/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('state_name', 'day_number'),
                'unique_together': {('state_name', 'day_number')},
            },
        ),
    ]
