# Generated by Django 5.0.7 on 2024-08-18 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255)),
                ('news_link', models.URLField(max_length=2083)),
                ('img_link', models.URLField(max_length=2083)),
            ],
        ),
    ]
