# Generated by Django 5.1.1 on 2024-10-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NationalNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255)),
                ('news_link', models.URLField(max_length=2083)),
                ('img_link', models.URLField(max_length=2083)),
            ],
        ),
    ]
