# Generated by Django 5.1.1 on 2024-10-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_keralanews'),
    ]

    operations = [
        migrations.CreateModel(
            name='KarnatakaNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255)),
                ('news_link', models.URLField(max_length=2083)),
                ('pubDate', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
            ],
        ),
    ]
