# Generated by Django 6.0.5 on 2026-05-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0004_karnatakanews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalnews',
            name='img_link',
        ),
        migrations.RemoveField(
            model_name='keralanews',
            name='img_link',
        ),
        migrations.RemoveField(
            model_name='nationalnews',
            name='img_link',
        ),
        migrations.AddField(
            model_name='globalnews',
            name='pubDate',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='globalnews',
            name='source',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='keralanews',
            name='pubDate',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='keralanews',
            name='source',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='nationalnews',
            name='pubDate',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='nationalnews',
            name='source',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='globalnews',
            name='headline',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='karnatakanews',
            name='headline',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='karnatakanews',
            name='pubDate',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='karnatakanews',
            name='source',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='keralanews',
            name='headline',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='nationalnews',
            name='headline',
            field=models.CharField(max_length=500),
        ),
    ]
