# Generated by Django 6.0.5 on 2026-05-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0005_remove_globalnews_img_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=100)),
                ('headline', models.CharField(max_length=500)),
                ('news_link', models.URLField(max_length=2083)),
                ('pubDate', models.CharField(blank=True, default='', max_length=255)),
                ('source', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='KarnatakaNews',
        ),
        migrations.DeleteModel(
            name='KeralaNews',
        ),
    ]
