# Generated by Django 5.0.7 on 2026-05-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="city",
            field=models.CharField(default="", max_length=120),
        ),
    ]
