# Generated by Django 6.0.5 on 2026-05-27 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_usersettings_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='email',
        ),
    ]
