# Generated by Django 6.0.5 on 2026-05-27 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_usersettings_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='name',
        ),
    ]
